name: brikoula_client_app
description: edl project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^1.4.4+4
  firebase_messaging: ^7.0.0
  provider: ^4.3.2+1
  shared_preferences: ^0.5.10
  transparent_image: ^1.0.0
  fluttertoast: ^7.1.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/circe-rounded/
    - assets/icons/

  fonts:
    - family: CirceRounded
      fonts:
        - asset: assets/fonts/circe-rounded/CirceRounded-Regular.otf
        - asset: assets/fonts/circe-rounded/CirceRounded-Light.otf
          weight: 300
        - asset: assets/fonts/circe-rounded/CirceRounded-Bold.otf
          weight: 900